name       : devscripts
version    : 2.18.9
release    : 5
source     :
    - https://salsa.debian.org/debian/devscripts/-/archive/v2.18.9/devscripts-v2.18.9.tar.bz2 : 37dfb10eca62a69f7a9be8c710044d0d7377b2a8f4a52370e4d67bdb6ef5c3e0
license    : GPL-2.0-or-later
summary    : Scripts for Debian package maintainers
description: |
    Scripts for Debian package maintainers
builddeps  :
    - pkgconfig(python3)
    - docbook-xml
    - dpkg
    - help2man
    - libwww-perl
    - perl-encode-locale
    - perl-file-desktopentry
    - perl-http-date
    - perl-http-message
    - perl-timedate
    - perl-uri
    - po4a
    - python-setuptools
# You fat bastid..
rundeps    :
    - dpkg
    - libwww-perl
    - perl-file-desktopentry
    - perl-encode-locale
    - perl-http-date
    - perl-http-message
    - perl-timedate
    - perl-uri
    - python-setuptools
build      : |
    # Inspired by Arch patch
    %patch -p1 < $pkgfiles/0001-Fix-docbook-versions-paths.patch
    make
install    : |
    %make_install
