name       : devscripts
version    : 2.15.10
release    : 3
source     :
    - http://ftp.debian.org/debian/pool/main/d/devscripts/devscripts_2.15.10.tar.xz : 8659779f03563aea6187f744b083cea2dfe637da2bb12ff52e38dd2e6f3762f9
license    : GPL-2.0
summary    : Scripts for Debian package maintainers
description: |
    Scripts for Debian package maintainers
builddeps  :
    - dpkg
    - perl-uri
    - libwww-perl
    - perl-http-message
    - perl-http-date
    - perl-encode-locale
    - perl-timedate
    - perl-file-desktopentry
    - docbook-xml
    - po4a
    - python-setuptools
    - pkgconfig(python-3.5)
# You fat bastid..
rundeps   :
    - dpkg
    - perl-uri
    - libwww-perl
    - perl-http-message
    - perl-http-date
    - perl-encode-locale
    - perl-timedate
    - perl-file-desktopentry
    - python-setuptools
build      : |
    # Inspired by Arch patch
    %patch -p1 < $pkgfiles/0001-Fix-docbook-versions-paths.patch
    make
install    : |
    %make_install
